const artworkData = [
    {
        title: 'Mona Lisa',
        description: 'A famous portrait painting by Leonardo da Vinci',
        artists: ['Leonardo da Vinci'],
        medium: 'Oil on poplar panel',
        image: 'https://example.com/mona-lisa.jpg',
        date: '1503-1519',
        tags: ['portrait', 'renaissance'],
        height: 77,
        width: 53,
        dbUser: 'admin',
    },
    {
        title: 'The Starry Night',
        description: 'A renowned oil painting by Vincent van Gogh',
        artists: ['Vincent van Gogh'],
        medium: 'Oil on canvas',
        image: 'https://example.com/starry-night.jpg',
        date: '1889',
        tags: ['landscape', 'post-impressionism'],
        height: 73.7,
        width: 92.1,
        dbUser: 'admin',
    },
    {
        title: 'The Kiss',
        description: 'A iconic painting by Gustav Klimt',
        artists: ['Gustav Klimt'],
        medium: 'Oil and gold leaf on canvas',
        image: 'https://example.com/the-kiss.jpg',
        date: '1907-1908',
        tags: ['portrait', 'symbolism', 'art nouveau'],
        height: 180,
        width: 180,
        dbUser: 'admin',
    },
    {
        title: 'The Persistence of Memory',
        description: 'A surrealist painting by Salvador Dalí',
        artists: ['Salvador Dalí'],
        medium: 'Oil on canvas',
        image: 'https://example.com/persistence-of-memory.jpg',
        date: '1931',
        tags: ['surrealism', 'landscape'],
        height: 24,
        width: 33,
        dbUser: 'admin',
    },
    {
        title: 'The Great Wave off Kanagawa',
        description: 'A famous woodblock print by Hokusai',
        artists: ['Hokusai'],
        medium: 'Woodblock print',
        image: 'https://example.com/great-wave.jpg',
        date: '1829-1833',
        tags: ['ukiyo-e', 'landscape'],
        height: 25.7,
        width: 37.8,
        dbUser: 'admin',
    },
    {
        title: 'The Son of Man',
        description: 'A surrealist self-portrait by René Magritte',
        artists: ['René Magritte'],
        medium: 'Oil on canvas',
        image: 'https://example.com/son-of-man.jpg',
        date: '1964',
        tags: ['surrealism', 'portrait', 'self-portrait'],
        height: 116,
        width: 89,
        dbUser: 'admin',
    },
    {
        title: 'Girl with a Pearl Earring',
        description: 'A famous portrait painting by Johannes Vermeer',
        artists: ['Johannes Vermeer'],
        medium: 'Oil on canvas',
        image: 'https://example.com/girl-with-pearl-earring.jpg',
        date: '1665',
        tags: ['portrait', 'baroque'],
        height: 44.5,
        width: 39,
        dbUser: 'admin',
    },
    {
        title: 'The Birth of Venus',
        description: 'An iconic painting by Sandro Botticelli',
        artists: ['Sandro Botticelli'],
        medium: 'Tempera on canvas',
        image: 'https://example.com/birth-of-venus.jpg',
        date: '1483-1485',
        tags: ['mythology', 'renaissance'],
        height: 172.5,
        width: 278.5,
        dbUser: 'admin',
    },
    {
        title: 'The Scream',
        description: 'An expressionist painting by Edvard Munch',
        artists: ['Edvard Munch'],
        medium: 'Oil, tempera, and pastel on cardboard',
        image: 'https://example.com/the-scream.jpg',
        date: '1893',
        tags: ['expressionism', 'landscape'],
        height: 91,
        width: 73.5,
        dbUser: 'admin',
    },
    {
        title: 'The Arnolfini Portrait',
        description: 'A famous portrait painting by Jan van Eyck',
        artists: ['Jan van Eyck'],
        medium: 'Oil on oak panel',
        image: 'https://example.com/arnolfini-portrait.jpg',
        date: '1434',
        tags: ['portrait', 'northern renaissance'],
        height: 82,
        width: 60,
        dbUser: 'admin',
    },
];

module.exports = artworkData;